### ISSUE TITLE
Zendesk data

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/get-into-teaching-crm-exports#6]
Do we want to feed data from Zendesk into BQ?

We'll probably need to be careful as any text fields could contain sensitive data, but the stats on the following things could be interesting:

* time and dates of contact
* a summary of question categories
* an idea of whether the answer was generic or bespoke
* how long it took to resolve the problem

Questions:

* [ ] can we link the ZD data to any other dataset?
* [ ] if the answer to the above question is no, will we actually gain anything by importing it?

@sh1van1P, @gemmadallmandfe - thoughts?

**Comment by gemmadallmandfe** [comment]
This Zendesk instance is owned by TPUK so we don't have direct access to the data.

We did have a discussion with TPUK and their implementation partner about what reporting is available, and what would be of interest to us, but this is more about aggregated reporting rather than raw data.

Not sure whether there is any scope to get a feed of summarised data - given that Zendesk has only just gone live, this might be one to explore later rather than sooner.

**Comment by peteryates** [comment]
Michelle has provided me with access to Zendesk. There's no direct integration but it's possible to create a view in ZD and export tickets via a CSV that can be pushed into GitHub.

Not sure it's going to be that useful, the support team also maintain a spreadsheet of current issues that might be a better source.

**Comment by gemmadallmandfe** [comment]
I think we are talking about two different Zendesks on this PR :-)

There is the Zendesk used by TPUK to manage their webchat / contact centre enquiries - we don't have access to this

And there is (separately) the Zendesk used by Michaela's support team which you have access to.

I agree - I'm not sure how much use the latter is going to be as a dataset. GIT support queries at the moment are generally about provider contact detail updates for the assessment only page, and queries about the verification emails (which we have hopefully addressed). In addition, people can sometimes put PII in the body of support queries, so I would be concerned about this being piped to BQ?

**Comment by peteryates** [comment]
Closing, we're pulling in support data via the support team's own (manual) tracker instead.
